// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvX8m3nGJYkW0MTH3tXRfVIihSC0PuukU',
    appId: '1:479655077132:web:2efb7d0adf0bac9f389529',
    messagingSenderId: '479655077132',
    projectId: 'weather-89965',
    authDomain: 'weather-89965.firebaseapp.com',
    storageBucket: 'weather-89965.appspot.com',
    measurementId: 'G-1FRR04RP6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACEebgdFeDlZMIexVfGlLrcD3fbVAz5Ys',
    appId: '1:479655077132:android:be7285cd42dd90b3389529',
    messagingSenderId: '479655077132',
    projectId: 'weather-89965',
    storageBucket: 'weather-89965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHcQhaUe6X3eTZiT5DD87d52rVzDftcQ',
    appId: '1:479655077132:ios:635405e1964add9a389529',
    messagingSenderId: '479655077132',
    projectId: 'weather-89965',
    storageBucket: 'weather-89965.appspot.com',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHcQhaUe6X3eTZiT5DD87d52rVzDftcQ',
    appId: '1:479655077132:ios:635405e1964add9a389529',
    messagingSenderId: '479655077132',
    projectId: 'weather-89965',
    storageBucket: 'weather-89965.appspot.com',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvX8m3nGJYkW0MTH3tXRfVIihSC0PuukU',
    appId: '1:479655077132:web:45a8fcc1b296d0a6389529',
    messagingSenderId: '479655077132',
    projectId: 'weather-89965',
    authDomain: 'weather-89965.firebaseapp.com',
    storageBucket: 'weather-89965.appspot.com',
    measurementId: 'G-QT0YXVD843',
  );

}